### ISSUE TITLE
Do we have g++, and gdc docker images?

### ISSUE THREAD

**Issue by mw66** [docker-library/gcc#105]
Hi,

I come here from: https://hub.docker.com/_/gcc/

I'm just wondering if  we have g++, and gdc (the D language) docker images?

Thanks.

**Comment by tianon** [comment]
g++ is already included in this image: https://github.com/docker-library/gcc/blob/b1e7fc69e4021bab505d420fddc57002ef04939e/14/Dockerfile#L125

That being said, I don't think we currently plan to expand the list of supported languages here, and for _most_ use cases I'd honestly suggest that most users are better off choosing a distribution they're comfortable with and installing `gcc` and related packages from the distribution (because otherwise, you'll spend a non-trivial amount of time fighting with other dependencies and libc/libstdc++ version conflicts).

**Comment by mw66** [comment]
OK, thanks.
