### ISSUE TITLE
installing BLAS, lapack with gcc-7

### ISSUE THREAD

**Issue by danshapero** [docker-library/gcc#40]
I'm trying to use the gcc-7 image to test a library that requires BLAS and lapack. When I run

`apt-get update && apt-get -yq libblas-dev libblas3`

for example, `apt-get` ends up installing gfortran-6 as a dependency, even though gfortran-7 is already on the system. I then get an error message to the effect of:

    update-alternatives: error: alternative path /usr/bin/gfortran doesn't exist
    dpkg: error processing package gfortran (--configure):
     subprocess installed post-installation script returned error exit status 2
    dpkg: dependency problems prevent configuration of libblas-dev:
     libblas-dev depends on gfortran; however:
      Package gfortran is not configured yet.

Installing BLAS and lapack with the gcc-5 and gcc-6 images goes off without a hitch. I'm not familiar enough with dpkg to figure out what's going wrong myself.

I've been using the gcc-5 and 6 images to test a library that I'm writing for compatibility with as many compilers as possible and they've been really helpful -- it would be great if I could get the gcc-7 image working too!

**Comment by yosifkit** [comment]
Ah, it looks like in Debian Stretch `libblas-dev` now depends on `gfortran`. This was not the case in Debian Jessie.  Since we compile gcc with fortran support, we had added a  `dpkg-divert` for `/usr/bin/gfortran` to ensure that the gcc version is used if fortran gets pulled in as a dependency for some library (like here).  It seems like we also need an `update-alternatives` like we have for `cc`.

You can get it working by adding `update-alternatives --install /usr/bin/gfortran gfortran /usr/local/bin/gfortran 999` before you install `libblas-dev`.  We might add it to the image as well, but we are not entirely sure of the possible breakage (cc @tianon).

**Comment by danshapero** [comment]
Cool, I just tried using `update-alternatives` for gfortran and it worked! I made a PR with the change, hopefully it doesn't break anything else.

Thanks for the quick reply!

**Comment by tianon** [comment]
Sorry for the delay.  I don't think we should add this to the image -- the reason we added it for `cc` is that `cc` is a generic wrapper/name for pointing to a compiler, and I think there are things in Debian that could potentially break if we point them at our compiled copy of `gfortran` instead.

Since there's a simple/usable workaround (using `update-alternatives`), I'm going to close this. :heart:
