### ISSUE TITLE
gcc-trunk build daily?

### ISSUE THREAD

**Issue by marehr** [docker-library/gcc#68]
Can you add a version for the current trunk which builds from source (https://github.com/gcc-mirror/gcc)?

And rebuild gcc-trunk every night?

We would like to be able to see regressions before a new release happens and in my experience they get fixed the fastest if you report them early.

**Comment by wglambert** [comment]
https://github.com/docker-library/julia/issues/25#issuecomment-434867037

Similar issues: https://github.com/docker-library/official-images/issues/1281, https://github.com/rust-lang-nursery/docker-rust/issues/5, https://github.com/docker-library/docker/issues/125

> Any `nightly` or `dev` image in the official images would still need to maintain the repeatability aspect.  All builds make heavy use of docker build cache so if the `RUN` line does not change, the image would not change.  Base images get updates and cause dependent images to rebuild and we don't want those situations to cause a version bump to the main software of the image.  The only other time an image gets built is via a commit in official-images that changes the respective `library/` file.  `eggdrop` is one image that has a `develop` build that they update once in a while (like https://github.com/docker-library/official-images/pull/3051).

https://github.com/docker-library/php/issues/825#issuecomment-492011060
Nightly builds aren't something we can feasibly maintain so I'm going to close this though since there's nothing actionable right now given that we really can't do proper nightly builds effectively. That being said, it shouldn't be too hard for someone to take our Dockerfile and create an image that mirrors ours but builds directly from a specific commit from upstream and publish/maintain it under a separate organization for users to consume.
